server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/geodb}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  jackson:
    default-property-inclusion: non_null

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}
